name = "dog-news"
account_id = "ff7a875e4fbaa2aa74528ab7e37bad66"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2021-11-12"
workers_dev = true